import Foundation

class RegionCodes {
    static func getRegionCode(fromCountryName countryName: String) -> String? {
        return RegionCodes.regionCodesByCountryName[countryName]
    }
    
    // The country names here should exactly match the names in the pricing matrix CSV file.
    // The two-letter region codes here must be ISO 3166-1 country codes (compatible with the Locale class):
    // https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
    static fileprivate let regionCodesByCountryName: Dictionary<String, String> = [
        
        "Hong Kong": "HK",
        "Portugal": "PT",
        "Honduras": "HN",
        "Paraguay": "PY",
        "Croatia": "HR",
        "Hungary": "HU",
        "Qatar": "QA",
        "Indonesia": "ID",
        "Ireland": "IE",
        "Israel": "IL",
        "United Arab Emirates": "AE",
        "Afghanistan": "AF",
        "India": "IN",
        "South Africa": "ZA",
        "Iraq": "IQ",
        "Iceland": "IS",
        "Albania": "AL",
        "Italy": "IT",
        "Armenia": "AM",
        "Argentina": "AR",
        "Zambia": "ZM",
        "Austria": "AT",
        "Australia": "AU",
        "Romania": "RO",
        "Bosnia and Herzegovina": "BA",
        "Barbados": "BB",
        "Serbia": "RS",
        "Russia": "RU",
        "Belgium": "BE",
        "Bulgaria": "BG",
        "Rwanda": "RW",
        "Japan": "JP",
        "Bahrain": "BH",
        "Bolivia": "BO",
        "Saudi Arabia": "SA",
        "Brazil": "BR",
        "Sweden": "SE",
        "Singapore": "SG",
        "Slovenia": "SI",
        "Belarus": "BY",
        "Slovakia": "SK",
        "Canada": "CA",
        "Congo, Democratic Republic of": "CD",
        "El Salvador": "SV",
        "Switzerland": "CH",
        "Cote D'Ivoire": "CI",
        "South Korea": "KR",
        "Chile": "CL",
        "Cameroon": "CM",
        "China": "CN",
        "Colombia": "CO",
        "Costa Rica": "CR",
        "Kazakhstan": "KZ",
        "Thailand": "TH",
        "Cyprus": "CY",
        "Czech Republic": "CZ",
        "Tonga": "TO",
        "Turkey": "TR",
        "Germany": "DE",
        "Taiwan": "TW",
        "Tanzania": "TZ",
        "Denmark": "DK",
        "Lithuania": "LT",
        "Luxembourg": "LU",
        "Latvia": "LV",
        "Dominican Republic": "DO",
        "Ukraine": "UA",
        "Libya": "LF",
        "Morocco": "MA",
        "Moldova": "MD",
        "Montenegro": "ME",
        "Ecuador": "EC",
        "United States": "US",
        "Myanmar": "MM",
        "Estonia": "EW",
        "Egypt": "EG",
        "Uruguay": "UY",
        "Uzbekistan": "UZ",
        "Malta": "MT",
        "Maldives": "MV",
        "Mexico": "MX",
        "Malaysia": "MY",
        "Spain": "ES",
        "Vietnam": "VN",
        "Nigeria": "NG",
        "Nicaragua": "NI",
        "Netherlands": "NL",
        "Vanuatu": "VU",
        "Norway": "NO",
        "Finland": "SF",
        "Nauru": "NR",
        "New Zealand": "NZ",
        "France": "FR",
        "Gabon": "GA",
        "United Kingdom": "UK",
        "Georgia": "GE",
        "Greece": "GR",
        "Guatemala": "GT",
        "Panama": "PA",
        "Kosovo": "XK",
        "Peru": "PE",
        "Philippines": "PH",
        "Pakistan": "PK",
        "Poland": "PL"
    ]
}
