import Foundation

class RegionCodes {
    static func getRegionCode(fromCountryName countryName: String) -> String? {
        return RegionCodes.regionCodesByCountryName[countryName]
    }
    
    // The country names here should exactly match the names in the pricing matrix CSV file.
    // The two-letter region codes here must be ISO 3166-1 country codes (compatible with the Locale class):
    // https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
    static fileprivate let regionCodesByCountryName: Dictionary<String, String> = [
        "United States" : "US",
        "Canada": "CA",
        "Mexico": "MX",
        "Australia": "AU",
        "New Zealand": "NZ",
        "Japan": "JP",
        "China": "CN",
        "Singapore": "SG",
        "Hong Kong": "HK",
        "Taiwan": "TW",
        "Indonesia": "ID",
        "India": "IN",
        "Russia": "RU",
        "Turkey": "TR",
        "Israel": "IL",
        "South Africa": "ZA",
        "Saudi Arabia": "SA",
        "United Arab Emirates": "AE",
        "United Kingdom": "UK",
        "Denmark": "DK",
        "Sweden": "SE",
        "Switzerland": "CH",
        "Norway": "NO",
        "Luxembourg": "LU",
        "Malta": "MT",
        "Cyprus": "CY",
        "Germany": "DE",
        "France": "FR",
        "Austria": "AT",
        "Bulgaria": "BG",
        "Estonia": "EE",
        "Slovakia": "SK",
        "Belgium": "BE",
        "Czech Republic": "CZ",
        "Latvia": "LV",
        "Lithuania": "LT",
        "Netherlands": "NL",
        "Spain": "ES",
        "Italy": "IT",
        "Slovenia": "SI",
        "Greece": "GR",
        "Ireland": "IE",
        "Poland": "PL",
        "Portugal": "PT",
        "Finland": "SF",
        "Romania": "RO",
        "Hungary": "HU",
        "Korea, Republic Of": "KR",
        "Thailand": "TH",
        "Iceland": "IS",
        "Croatia": "HR",
        "Albania": "AL",
        "Malaysia": "MY",
        "Philippines": "PH",
        "Vietnam": "VN",
        "Egypt": "EG",
        "Kazakhstan": "KZ",
        "Qatar": "QA",
        "Nigeria": "NG",
        "Pakistan": "OK",
        "Tanzania, United Republic Of": "TZ",
        "Chile": "CL",
        "Colombia": "CO",
        "Peru": "PE",
        "Brazil": "BR"
    ]
}
